version: '3'
services:
    prisma:
        image: prismagraphql/prisma:1.34
        restart: always
        ports:
            - '4466:4466'
        environment:
            PRISMA_CONFIG: |
                port: 4466
                managementApiSecret: 234r679804urfhnc232
                databases:
                  default:
                    connector: mongo
                    uri: mongodb+srv://prisma-admin:dgsyg6t3ybjncec423tgr@prisma-cluster-ppnyn.mongodb.net/prisma-database?retryWrites=true&w=majority
